name: Regenerate Protobufs

on:
  workflow_dispatch:

jobs:
  regenerate-protobufs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
        
    - name: Regenerate protobuf files
      run: |
        # Navigate to protobufs/meshtastic and temporarily rename deviceonly.proto
        cd ./protobufs/meshtastic/
        mv deviceonly.proto deviceonly.ignoreproto
        cd ../../
        
        # Use protoc from NuGet package (same as existing scripts)
        ~/.nuget/packages/google.protobuf.tools/3.29.3/tools/linux_x64/protoc -I=protobufs --csharp_out=./Meshtastic/Generated --csharp_opt=base_namespace=Meshtastic.Protobufs ./protobufs/meshtastic/*.proto
        
        # Restore deviceonly.proto
        cd ./protobufs/meshtastic/
        mv deviceonly.ignoreproto deviceonly.proto
        cd ../../
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and create pull request
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: regenerate protobuf files'
        title: 'chore: regenerate protobuf files'
        body: |
          This pull request contains updated C# protobuf files generated from the latest proto definitions.
          
          Generated by the "Regenerate Protobufs" GitHub Action workflow.
        branch: regen-protobufs
        delete-branch: true
        add-paths: |
          Meshtastic/Generated/
    
    - name: No changes detected
      if: steps.verify-changed-files.outputs.changed == 'false'
      run: echo "No changes detected in generated protobuf files."
